
import { Geist, Geist_Mono } from "next/font/google";
import "./../../globals.css";
import CompanyHeader from "@/Components/Companies/CompanyHeader";
import CompanySidebar from "@/Components/Companies/CompanySidebar";

export const metadata = {
    title: "Job Website",
    description: "Generated by create next app",
};

// Main layout component for company-related pages
export default function Layout({ children }) {



    return (
        <div className="min-h-screen bg-gray-100 flex flex-col">
            {/* Company Header */}
            <div className="flex flex-1">
                {/* Sidebar */}
                <CompanySidebar />
                {/* Main Content Area */}
                <div className="flex-1 flex flex-col">
                    <CompanyHeader className="" />
                    <div className="flex-1 md:px-10 md:py-5 p-5 bg-white ">
                        {children}
                    </div>
                </div>
            </div>

        </div>
    );
}
