import { Geist, Geist_Mono } from "next/font/google";
import "./../../../globals.css";
import CompanyProfileHeader from "@/Components/Companies/Profile/CompanyProfileHeader";

export const metadata = {
    title: "Job Website",
    description: "Generated by create next app",
};

// not root layout this is main layout

export default function Layout({ children }) {
    return (
        <div>
            <CompanyProfileHeader />
            {children}
        </div>
    );
}
